### ISSUE TITLE
Wall and Floor Sprites

### ISSUE THREAD

**Issue by aloenobilis** [nluqo/broughlike-tutorial#4]
Hi,
Stuck on "Drawing Map Tiles" Stage 2. There is no reference or example of where the floor and wall sprites should go.

**Comment by nluqo** [comment]
There are little drawing sections whenever you need to draw a sprite and you'll just put them in order going left to right in your spritesheet.

You can also compare against the completed versions of each stage, so this is the completed Stage 2 spritesheet: https://github.com/nluqo/broughlike-tutorial/blob/master/docs/completed/stage2/spritesheet.png

If you were able to follow the part about drawing the player/corpse, this should be no different. Is there a way I could explain it better?

**Comment by aloenobilis** [comment]
Thanks for the quick response. That makes sense!
So the constructor for the sprite param specifics which sprite will be used in the spritesheet. Not used to working with a "film strip" approach, rather individual assets.

I think a progression of the spritesheet would make it more obvious, otherwise enjoying it so far :)
